docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:

environments:
  production:
    routes:
      - storybook:
        - "visualise.myvictoria.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
      - example:
        - "example.visualise.myvictoria.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
  master:
    routes:
      - storybook:
        - "master.visualise.myvictoria.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
      - example:
        - "example.master.visualise.myvictoria.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
  develop:
    routes:
      - storybook:
        - "develop.visualise.myvictoria.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
      - example:
        - "example.develop.visualise.myvictoria.vic.gov.au":
            tls-acme: 'false'
            insecure: Allow
            hsts: max-age=31536000
