FROM amazeeio/node:14-builder as builder

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'yarn.lock'
COPY examples/vue-example-app/package.json ./
COPY examples/vue-example-app/yarn.lock ./

# install project dependencies
RUN yarn install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY examples/vue-example-app/ .

ARG VUE_APP_COVID_MAP_BASEMAP_PROVIDER
ENV VUE_APP_COVID_MAP_BASEMAP_PROVIDER ${VUE_APP_COVID_MAP_BASEMAP_PROVIDER}
ARG VUE_APP_COVID_MAP_RADIUS
ENV VUE_APP_COVID_MAP_RADIUS ${VUE_APP_COVID_MAP_RADIUS}
ARG VUE_APP_COVID_MAP_GEOCODE_PROVIDER
ENV VUE_APP_COVID_MAP_GEOCODE_PROVIDER ${VUE_APP_COVID_MAP_GEOCODE_PROVIDER}
ARG VUE_APP_COVID_MAP_VICMAP_API_KEY
ENV VUE_APP_COVID_MAP_VICMAP_API_KEY ${VUE_APP_COVID_MAP_VICMAP_API_KEY}
ARG VUE_APP_COVID_MAP_LABEL
ENV VUE_APP_COVID_MAP_LABEL ${VUE_APP_COVID_MAP_LABEL}

# build app for production with minification
RUN yarn build

EXPOSE 3000
CMD [ "http-server", "dist", "-p", "3000", "--proxy", "http://localhost:3000?" ]
