export const annotation1 = {
  annotations: [
    {
      'type': 'box',
      xScaleID: 'secondary',
      yScaleID: 'primary',
      'yMin': 24,
      'yMax': 25,
      'xMin': -0.5,
      'xMax': 2.5,
      'borderWidth': 1,
      'backgroundColor': 'rgba(200,60,60,0.25)',
      'borderColor': 'rgba(200,60,60,0.25)'
    },
    {
      'type': 'box',
      xScaleID: 'secondary',
      yScaleID: 'primary',
      'yMin': 27,
      'yMax': 28,
      'xMin': 2.5,
      'xMax': 5.5,
      'borderWidth': 1,
      'backgroundColor': 'rgba(200,60,60,0.25)',
      'borderColor': 'rgba(200,60,60,0.25)'
    },
    {
      'type': 'box',
      xScaleID: 'secondary',
      yScaleID: 'primary',
      'yMin': 28,
      'yMax': 50,
      'xMin': 0.5,
      'xMax': 0.5,
      'borderWidth': 1,
      'backgroundColor': '#666',
      'borderColor': '#666'
    },
    {
      'type': 'box',
      xScaleID: 'secondary',
      yScaleID: 'primary',
      'yMin': 31,
      'yMax': 54,
      'xMin': 3.5,
      'xMax': 3.5,
      'borderWidth': 1,
      'backgroundColor': '#666',
      'borderColor': '#666'
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 1,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'sans-serif',
        fontSize: 12,
        fontStyle: 'bold',
        fontColor: 'rgba(200,60,60,0.85)',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -5,
        yAdjust: 55,
        enabled: true,
        content: 'Test label 1',
        rotation: 90
      }
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 4,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'sans-serif',
        fontSize: 12,
        fontStyle: 'bold',
        fontColor: 'rgba(200,60,60,0.85)',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -5,
        yAdjust: 35,
        enabled: true,
        content: 'Test label 2',
        rotation: 90
      }
    }
  ]
}

export const annotation2 = {
  annotations: [
    {
      type: 'box',
      xScaleID: 'secondary',
      yScaleID: 'primary',
      yMin: 26.1,
      yMax: 150,
      xMin: -0.4,
      xMax: -0.4,
      borderWidth: 1,
      borderColor: '#011a3c'
    },
    {
      type: 'box',
      xScaleID: 'secondary',
      yScaleID: 'primary',
      yMin: 26.1,
      yMax: 26.1,
      xMin: -0.4,
      xMax: 9.3,
      borderWidth: 1,
      borderColor: '#011a3c'
    },
    {
      type: 'box',
      xScaleID: 'secondary',
      yScaleID: 'primary',
      yMin: 58.56,
      yMax: 150,
      xMin: 9.5,
      xMax: 9.5,
      borderWidth: 1,
      borderColor: '#011a3c'
    },
    {
      type: 'box',
      xScaleID: 'secondary',
      yScaleID: 'primary',
      yMin: 58.56,
      yMax: 58.56,
      xMin: 9.5,
      xMax: 20,
      borderWidth: 1,
      borderColor: '#011a3c'
    },
    {
      type: 'box',
      xScaleID: 'secondary',
      yScaleID: 'primary',
      yMin: 64.25,
      yMax: 150,
      xMin: 14.5,
      xMax: 14.5,
      borderWidth: 1,
      borderColor: '#011a3c'
    },
    {
      type: 'box',
      xScaleID: 'secondary',
      yScaleID: 'primary',
      yMin: 64.25,
      yMax: 64.25,
      xMin: 14.5,
      xMax: 20,
      borderWidth: 1,
      borderColor: '#011a3c'
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 0,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'yMin': 28,
      'yMax': 50,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'VIC-REGULAR, Arial, Helvetica, sans-serif',
        fontSize: 12,
        fontStyle: 'normal',
        fontColor: '#011a3c',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -26,
        yAdjust: 5,
        enabled: true,
        content: 'Average GII',
        rotation: 90
      }
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 0,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'yMin': 28,
      'yMax': 50,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'VIC-REGULAR, Arial, Helvetica, sans-serif',
        fontSize: 12,
        fontStyle: 'normal',
        fontColor: '#011a3c',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -47,
        yAdjust: 18,
        enabled: true,
        content: '2005-06 to 2014-15',
        rotation: 90
      }
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 0,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'yMin': 28,
      'yMax': 50,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'VIC-REGULAR, Arial, Helvetica, sans-serif',
        fontSize: 12,
        fontStyle: 'normal',
        fontColor: '#011a3c',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -31,
        yAdjust: 31,
        enabled: true,
        content: '($26.1 million)',
        rotation: 90
      }
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 9,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'yMin': 28,
      'yMax': 50,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'VIC-REGULAR, Arial, Helvetica, sans-serif',
        fontSize: 12,
        fontStyle: 'normal',
        fontColor: '#011a3c',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -61,
        yAdjust: 5,
        enabled: true,
        content: 'Average GII',
        rotation: 90
      }
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 9,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'yMin': 28,
      'yMax': 50,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'VIC-REGULAR, Arial, Helvetica, sans-serif',
        fontSize: 12,
        fontStyle: 'normal',
        fontColor: '#011a3c',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -80,
        yAdjust: 18,
        enabled: true,
        content: '2015-16 to 2023-24',
        rotation: 90
      }
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 9,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'yMin': 28,
      'yMax': 50,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'VIC-REGULAR, Arial, Helvetica, sans-serif',
        fontSize: 12,
        fontStyle: 'normal',
        fontColor: '#011a3c',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -71,
        yAdjust: 31,
        enabled: true,
        content: '($58.56 million)',
        rotation: 90
      }
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 15,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'yMin': 28,
      'yMax': 50,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'VIC-REGULAR, Arial, Helvetica, sans-serif',
        fontSize: 12,
        fontStyle: 'normal',
        fontColor: '#011a3c',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -20,
        yAdjust: 5,
        enabled: true,
        content: 'Average GII',
        rotation: 90
      }
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 15,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'yMin': 28,
      'yMax': 50,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'VIC-REGULAR, Arial, Helvetica, sans-serif',
        fontSize: 12,
        fontStyle: 'normal',
        fontColor: '#011a3c',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -41,
        yAdjust: 18,
        enabled: true,
        content: '2020-21 to 2023-24',
        rotation: 90
      }
    },
    {
      'type': 'line',
      'mode': 'vertical',
      scaleID: 'secondary',
      'value': 15,
      'borderColor': 'rgba(0,0,0,0)',
      'borderWidth': 0,
      'yMin': 28,
      'yMax': 50,
      'label': {
        backgroundColor: 'rgba(0,0,0,0)',
        fontFamily: 'VIC-REGULAR, Arial, Helvetica, sans-serif',
        fontSize: 12,
        fontStyle: 'normal',
        fontColor: '#011a3c',
        xPadding: 6,
        yPadding: 6,
        cornerRadius: 6,
        position: 'top',
        xAdjust: -31,
        yAdjust: 31,
        enabled: true,
        content: '($64.25 million)',
        rotation: 90
      }
    }
  ]
}
